name: quick_bid
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  go_router: ^16.2.4
  timer_builder: ^2.0.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  network_image: ^0.1.1
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  flutter_markdown: ^0.7.7+1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_test_goldens: ^0.0.7
  golden_toolkit: ^0.15.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/mock_photo.png
